---
name: Test & Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  validate:
    name: "tests & coverage"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: python -m pip install hatch
      - run: hatch fmt --check
      - run: hatch test
      - run: hatch run types:check

  semantic_release:
    name: "semantic release"
    runs-on: ubuntu-latest

    if: github.event_name == 'push'

    # Make sure tests pass before running.
    needs:
      - validate

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      # `python-semantic-release` will run `hatch build`.
      - run: python -m pip install hatch
      - uses: python-semantic-release/python-semantic-release@v9.8.3

  pypi:
    name: "publish to PyPi"
    runs-on: ubuntu-latest

    if: github.event_name == 'release'

    needs:
      - validate

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - run: python -m pip install hatch
      # Tests should have already run in the `validate` job; just run
      # them again as a sanity check.
      - run: hatch test
      - run: hatch build
      - run: hatch publish
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
